config/routes.rb
Rails.application.routes.draw do
  resources :basketball_stats
  devise_for :users
  root 'basketball_stats#index'
end

app/models/basketball_stat.rb
class BasketballStat < ActiveRecord::Base
end

app/models/stats_basketball.rb
class StatsBasketball < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/basketball_stats_controller.rb
class BasketballStatsController < ApplicationController
  before_action :set_basketball_stat, only: [:show, :edit, :update, :destroy]

  # GET /basketball_stats
  # GET /basketball_stats.json
  def index
    @basketball_stats = BasketballStat.all
  end

  # GET /basketball_stats/1
  # GET /basketball_stats/1.json
  def show
  end

  # GET /basketball_stats/new
  def new
    @basketball_stat = BasketballStat.new
  end

  # GET /basketball_stats/1/edit
  def edit
  end

  # POST /basketball_stats
  # POST /basketball_stats.json
  def create
    @basketball_stat = BasketballStat.new(basketball_stat_params)

    respond_to do |format|
      if @basketball_stat.save
        format.html { redirect_to @basketball_stat, notice: 'Basketball stat was successfully created.' }
        format.json { render :show, status: :created, location: @basketball_stat }
      else
        format.html { render :new }
        format.json { render json: @basketball_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basketball_stats/1
  # PATCH/PUT /basketball_stats/1.json
  def update
    respond_to do |format|
      if @basketball_stat.update(basketball_stat_params)
        format.html { redirect_to @basketball_stat, notice: 'Basketball stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @basketball_stat }
      else
        format.html { render :edit }
        format.json { render json: @basketball_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basketball_stats/1
  # DELETE /basketball_stats/1.json
  def destroy
    @basketball_stat.destroy
    respond_to do |format|
      format.html { redirect_to basketball_stats_url, notice: 'Basketball stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basketball_stat
      @basketball_stat = BasketballStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basketball_stat_params
      params.require(:basketball_stat).permit(:total_points, :two_pointers_made, :two_pointers_missed, :three_pointers_made, :three_pointers_missed, :field_goal_percentage, :free_throws_made, :free_throws_missed, :assists, :rebounds, :blocks, :steals, :fouls, :technical_fouls)
    end
end

app/controllers/stats_basketballs_controller.rb
class StatsBasketballsController < ApplicationController
  before_action :set_stats_basketball, only: [:show, :edit, :update, :destroy]

  # GET /stats_basketballs
  # GET /stats_basketballs.json
  def index
    @stats_basketballs = StatsBasketball.all
  end

  # GET /stats_basketballs/1
  # GET /stats_basketballs/1.json
  def show
  end

  # GET /stats_basketballs/new
  def new
    @stats_basketball = StatsBasketball.new
  end

  # GET /stats_basketballs/1/edit
  def edit
  end

  # POST /stats_basketballs
  # POST /stats_basketballs.json
  def create
    @stats_basketball = StatsBasketball.new(stats_basketball_params)

    respond_to do |format|
      if @stats_basketball.save
        format.html { redirect_to @stats_basketball, notice: 'Stats basketball was successfully created.' }
        format.json { render :show, status: :created, location: @stats_basketball }
      else
        format.html { render :new }
        format.json { render json: @stats_basketball.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats_basketballs/1
  # PATCH/PUT /stats_basketballs/1.json
  def update
    respond_to do |format|
      if @stats_basketball.update(stats_basketball_params)
        format.html { redirect_to @stats_basketball, notice: 'Stats basketball was successfully updated.' }
        format.json { render :show, status: :ok, location: @stats_basketball }
      else
        format.html { render :edit }
        format.json { render json: @stats_basketball.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats_basketballs/1
  # DELETE /stats_basketballs/1.json
  def destroy
    @stats_basketball.destroy
    respond_to do |format|
      format.html { redirect_to stats_basketballs_url, notice: 'Stats basketball was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stats_basketball
      @stats_basketball = StatsBasketball.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stats_basketball_params
      params.require(:stats_basketball).permit(:total_points, :two_pointers_made, :two_pointers_missed, :three_pointers_made, :three_pointers_missed, :field_goal_percentage, :free_throws_made, :free_throws_missed, :assists, :rebounds, :blocks, :steals, :fouls, :technical_fouls)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basketball_stats_helper.rb
module BasketballStatsHelper
end

app/helpers/stats_basketballs_helper.rb
module StatsBasketballsHelper
end

app/views/basketball_stats/_form.html.erb
<%= form_for(@basketball_stat) do |f| %>
  <% if @basketball_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basketball_stat.errors.count, "error") %> prohibited this basketball_stat from being saved:</h2>

      <ul>
      <% @basketball_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total_points %><br>
    <%= f.text_field :total_points %>
  </div>
  <div class="field">
    <%= f.label :two_pointers_made %><br>
    <%= f.text_field :two_pointers_made %>
  </div>
  <div class="field">
    <%= f.label :two_pointers_missed %><br>
    <%= f.text_field :two_pointers_missed %>
  </div>
  <div class="field">
    <%= f.label :three_pointers_made %><br>
    <%= f.text_field :three_pointers_made %>
  </div>
  <div class="field">
    <%= f.label :three_pointers_missed %><br>
    <%= f.text_field :three_pointers_missed %>
  </div>
  <div class="field">
    <%= f.label :field_goal_percentage %><br>
    <%= f.text_field :field_goal_percentage %>
  </div>
  <div class="field">
    <%= f.label :free_throws_made %><br>
    <%= f.text_field :free_throws_made %>
  </div>
  <div class="field">
    <%= f.label :free_throws_missed %><br>
    <%= f.text_field :free_throws_missed %>
  </div>
  <div class="field">
    <%= f.label :assists %><br>
    <%= f.text_field :assists %>
  </div>
  <div class="field">
    <%= f.label :rebounds %><br>
    <%= f.text_field :rebounds %>
  </div>
  <div class="field">
    <%= f.label :blocks %><br>
    <%= f.text_field :blocks %>
  </div>
  <div class="field">
    <%= f.label :steals %><br>
    <%= f.text_field :steals %>
  </div>
  <div class="field">
    <%= f.label :fouls %><br>
    <%= f.text_field :fouls %>
  </div>
  <div class="field">
    <%= f.label :technical_fouls %><br>
    <%= f.text_field :technical_fouls %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basketball_stats/edit.html.erb
<h1>Editing Basketball Stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @basketball_stat %> |
<%= link_to 'Back', basketball_stats_path %>

app/views/basketball_stats/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'log out', destroy_user_session_path, :method => :delete %>

<h1>Listing Basketball Stats</h1>

<table>
  <thead>
    <tr>
      <th>Total points</th>
      <th>Two pointers made</th>
      <th>Two pointers missed</th>
      <th>Three pointers made</th>
      <th>Three pointers missed</th>
      <th>Field goal percentage</th>
      <th>Free throws made</th>
      <th>Free throws missed</th>
      <th>Assists</th>
      <th>Rebounds</th>
      <th>Blocks</th>
      <th>Steals</th>
      <th>Fouls</th>
      <th>Technical fouls</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basketball_stats.each do |basketball_stat| %>
      <tr>
        <td><%= basketball_stat.total_points %></td>
        <td><%= basketball_stat.two_pointers_made %></td>
        <td><%= basketball_stat.two_pointers_missed %></td>
        <td><%= basketball_stat.three_pointers_made %></td>
        <td><%= basketball_stat.three_pointers_missed %></td>
        <td><%= basketball_stat.field_goal_percentage %></td>
        <td><%= basketball_stat.free_throws_made %></td>
        <td><%= basketball_stat.free_throws_missed %></td>
        <td><%= basketball_stat.assists %></td>
        <td><%= basketball_stat.rebounds %></td>
        <td><%= basketball_stat.blocks %></td>
        <td><%= basketball_stat.steals %></td>
        <td><%= basketball_stat.fouls %></td>
        <td><%= basketball_stat.technical_fouls %></td>
        <td><%= link_to 'Show', basketball_stat %></td>
        <td><%= link_to 'Edit', edit_basketball_stat_path(basketball_stat) %></td>
        <td><%= link_to 'Destroy', basketball_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basketball stat', new_basketball_stat_path %>

app/views/basketball_stats/new.html.erb
<h1>New Basketball Stat</h1>

<%= render 'form' %>

<%= link_to 'Back', basketball_stats_path %>

app/views/basketball_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total points:</strong>
  <%= @basketball_stat.total_points %>
</p>

<p>
  <strong>Two pointers made:</strong>
  <%= @basketball_stat.two_pointers_made %>
</p>

<p>
  <strong>Two pointers missed:</strong>
  <%= @basketball_stat.two_pointers_missed %>
</p>

<p>
  <strong>Three pointers made:</strong>
  <%= @basketball_stat.three_pointers_made %>
</p>

<p>
  <strong>Three pointers missed:</strong>
  <%= @basketball_stat.three_pointers_missed %>
</p>

<p>
  <strong>Field goal percentage:</strong>
  <%= @basketball_stat.field_goal_percentage %>
</p>

<p>
  <strong>Free throws made:</strong>
  <%= @basketball_stat.free_throws_made %>
</p>

<p>
  <strong>Free throws missed:</strong>
  <%= @basketball_stat.free_throws_missed %>
</p>

<p>
  <strong>Assists:</strong>
  <%= @basketball_stat.assists %>
</p>

<p>
  <strong>Rebounds:</strong>
  <%= @basketball_stat.rebounds %>
</p>

<p>
  <strong>Blocks:</strong>
  <%= @basketball_stat.blocks %>
</p>

<p>
  <strong>Steals:</strong>
  <%= @basketball_stat.steals %>
</p>

<p>
  <strong>Fouls:</strong>
  <%= @basketball_stat.fouls %>
</p>

<p>
  <strong>Technical fouls:</strong>
  <%= @basketball_stat.technical_fouls %>
</p>

<%= link_to 'Edit', edit_basketball_stat_path(@basketball_stat) %> |
<%= link_to 'Back', basketball_stats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StatsKeeper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>